<?php

namespace ShopBundle\Repository;

/**
 * CustomerAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
