<?php

namespace ShopBundle\Repository;

/**
 * PurchaseHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
