<?php

namespace ShopBundle\Repository;

/**
 * PurchaceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
